# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d7adbde7487a0ae8b04f491b363d3a3059740ac69ef35490b9a7d67f1e0df29cbeca6bde928e854a8c345c1b7046c6a8040ac449e9ee57250b7c51e3385b739

test:
  secret_key_base: 512f43490341f07e89dc91cdefccf15660d7003c5480dd638874c32118e4a7b9b266e1cd05078341cf297ccb36a1fe5513ff571dcc4bb0efac3049be5868677b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 512f43490341f07e89dc91cdefccf15660d7003c5480dd638874c32118e4a7b9b266e1cd05078341cf297ccb36a1fe5513ff571dcc4bb0efac3049be586867njn
